version: '3'
x-common: &common
  build:
    context: ./frontend/
    dockerfile: Dockerfile
  volumes:
    - ./frontend:/usr/src/app
  environment:
    - CHOKIDAR_USEPOLLING=true

services:
  web:
    <<: *common
    ports:
      - '5174:5174'
    command: sh -c "yarn dev --host"

  storybook:
    <<: *common
    ports:
      - '6006:6006'
    command: sh -c "yarn storybook"

  db:
    image: mysql:8.0.34
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
  api:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: bundle exec puma -C config/puma.rb
    volumes:
      - ./backend:/sample
      - public-data:/sample/public
      - tmp-data:/sample/tmp
      - log-data:/sample/log
    environment:
      RAILS_ENV: development
    depends_on:
      - db
  nginx:
    build:
      context: ./backend/nginx
      dockerfile: Dockerfile
    volumes:
      - public-data:/sample/public
      - tmp-data:/sample/tmp
    ports:
      - 80:80
    depends_on:
      - api
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: