name: 'Chromatic Deployment'

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: directies
        run: ls -la

      # - name: Install dependencies
      #   working-directory: ./frontend/react-app
      #   run: yarn

      # - name: Run Chromatic
      #   uses: chromatic/cli-action@v1
      #   with:
      #     projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     workingDir: ./frontend/react-app