name: 'Chromatic Deployment'

on: 'push'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - working-directory: ./frontend/react-app
        run: yarn
      - uses: chromatic/cli-action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./frontend/react-app